### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by codingmusician** [seregazhuk/php-pinterest-bot#225]
Is there a way to request different pages? I know we can set a limit for searches and other things, but it'd be nice to set a limit and page. We'd like to be able to get the first 100 results, then the 2nd 100 results is a separate call. Is there any way to do that currently? If not, are there plans to add this in?

**Comment by seregazhuk** [comment]
The problem is that Pinterest doesn't provide pagination. With every request it returns *bookmarks* - an offset string to get the next batch of the results. There is no way to get the second batch, without going through the first one.
I think I can implement something like this:
```php
$results = $bot->pins->search('query', 100)->skip(100)->get();
```

But behind the scenes, a bot will go through the first 100 results.

**Comment by seregazhuk** [comment]
@codingmusician, done! In version 5.1.2 you can use pagination as I mentioned above:
```php
// to skip first 100 results
$results = $bot->pins->search('query', 100)->skip(100)->get();
```

**Comment by codingmusician** [comment]
Awesome! Thanks!
