### ISSUE TITLE
tmpnam() being used for cookies

### ISSUE THREAD

**Issue by codingmusician** [seregazhuk/php-pinterest-bot#290]
Some of our accounts were getting flagged for abnormal login behavior, which usually occurs when you log in over and over again, instead of using cookies. We looked at our /tmp file (where the cookie files are being stored) and noticed that we had some strange filenames, like pinterest_cookie_eLe1Uw, pinterest_cookie_DYUtox. We also saw the cookie files that had actual usernames in them.

I found the part in the code where tmpname() was being used to create a cookie, which occurs when no username is passed through. I guess this is occuring somewhere, but I can't seem to find it.

Any idea why this would be happening?

**Comment by seregazhuk** [comment]
Hi, @codingmusician 
Yes, the bot generates a random cookie-file name, if you don't log in, so you can create several independent instances of bot. If you log in, it saves on disk a cookie with your login, so next time the bot will load this cookie instead of the login request.

What is your problem? Some of your accounts cannot login?

**Comment by seregazhuk** [comment]
I think that I should improve the bot, so it could delete the cookies when you don't log in. Because if you use the bot frequently your /tmp folder is full of these cookie-files. Now you can do it explicitly with `$bot->getHttpClient()->removeCookies();` This method removes currently loaded cookie-file.

**Comment by codingmusician** [comment]
I'm not sure what the problem is, exactly. At times, it can't find the _auth cookie, so it forces it to log in using the credentials. I was looking through the code and saw that when the autoLogin fails, it deletes the cookie and the reference to the cookie file, then tries to log in. What did NOT see was where it re-created the cookie file when it tried to log in again. We don't have any instances in our scripts where we do not log in.

What I did, though, is modify the removeCookies() method to delete the cookie file, then re-create the cookie file with the same name, so that if it tries to log in again, it uses the same cookie file. I'm monitoring our cookie files and so far, so good. Last time, it took a few days before I saw the problem occur. If you'd like, I'll keep you updated on the result.

**Comment by seregazhuk** [comment]
I've found it! You were right. When autologin fails, it removes the cookie file. Then you make a login request and it creates a cookie but... with a random file name. So, next time when you try to log in with this username, it again cannot find the saved cookie file.
I'll fix it now.

**Comment by seregazhuk** [comment]
@codingmusician I've published a new release, please update (v5.4.3)
